"""
Global settings for the MATERIAL MASTER pipeline.
Edit this file to configure output format and PRODUCT CATALOG
"""
from pathlib import Path

# Output
OUTPUT_FORMAT: str = "csv"
OUTPUT_DIR = Path("../../data/catalog/material_master")


SCHEMA = {
    "product_id":    "string",
    "sku":           "string",
    "name":          "string",
    "description":   "string",
    "price":         "float64",
    "currency":      "string",
    "weight_kg":     "float64",
    "dimensions_cm": "string",
    "is_active":     "boolean",  # Read "True"/"False" correctly from CSV
}


#                category     count      price_range
# 0            Taco Robots       10       $3,799.00 – $7,200.00
# 1            Accessories       5        $89.00 – $450.00
# 2            Consumables       3        $22.50 – $45.00
# 3    Software & Services       2        $79.00 – $1,200.00
PRODUCT_CATALOG_DATA = [
    {
        "product_id":    "TRBT-001",
        "sku":           "TRBT-NEURALCARNE-PRO",
        "name":          "NeuralCarne Pro",
        "description":   "AI-powered beef barbacoa robot trained on 1M abuela recipes. 99.4% flavor accuracy. Auto tortilla press included.",
        "price":         4899.99,
        "currency":      "USD",
        "weight_kg":     38.5,
        "dimensions_cm": "60x45x120",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-002",
        "sku":           "TRBT-ALPHAPASTOR-V2",
        "name":          "AlphaGrill Pastor v2",
        "description":   "Al pastor robot with RL marinade optimizer and laser pineapple slicer. 220 tacos/hr.",
        "price":         5250.00,
        "currency":      "USD",
        "weight_kg":     45.0,
        "dimensions_cm": "70x50x130",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-003",
        "sku":           "TRBT-DEEPFRY-GPT",
        "name":          "DeepFryer-GPT",
        "description":   "Carnitas frying robot with thermal neural net. Oil temp precision ±0.1°C. 99.7% crispiness SLA.",
        "price":         3799.00,
        "currency":      "USD",
        "weight_kg":     52.0,
        "dimensions_cm": "75x55x110",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-004",
        "sku":           "TRBT-BERT-GRILL-3",
        "name":          "BERT-asada Grill 3.0",
        "description":   "Bidirectional carne asada robot that scans meat protein structure before grilling. Lime sprayer included.",
        "price":         6100.00,
        "currency":      "USD",
        "weight_kg":     60.0,
        "dimensions_cm": "80x60x140",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-005",
        "sku":           "TRBT-LLAMA2-LENGUA",
        "name":          "Llama-2 Lengua Cooker",
        "description":   "8-hour slow cooker supervised by Llama-2. Auto jalapeño pickler and avocado cream dispenser.",
        "price":         5500.00,
        "currency":      "USD",
        "weight_kg":     70.0,
        "dimensions_cm": "85x65x150",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-006",
        "sku":           "TRBT-TRANSFORMER-POLLO",
        "name":          "Transformer Pollo Bot",
        "description":   "Grilled chicken robot with attention-weighted chipotle marinade. Each bite contextually linked to the previous.",
        "price":         4100.00,
        "currency":      "USD",
        "weight_kg":     41.0,
        "dimensions_cm": "65x48x125",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-007",
        "sku":           "TRBT-GANCAMOLE-SHRIMP",
        "name":          "GANcamole Shrimp Unit",
        "description":   "Grilled shrimp robot with GAN-generated guacamole module. Avocado texture hallucinated from 200k images.",
        "price":         5800.00,
        "currency":      "USD",
        "weight_kg":     47.5,
        "dimensions_cm": "72x52x135",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-008",
        "sku":           "TRBT-RAG-RAJAS",
        "name":          "RAG Rajas Vegetarian",
        "description":   "Poblano strip and cream robot. Retrieves Oaxacan recipes from a 500k-document knowledge base.",
        "price":         3600.00,
        "currency":      "USD",
        "weight_kg":     35.0,
        "dimensions_cm": "58x42x115",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-009",
        "sku":           "TRBT-DIFFUSION-COCHINITA",
        "name":          "Diffusion Cochinita XL",
        "description":   "Cochinita pibil robot whose color and texture are iteratively denoised to perfection. Habanero curtido module.",
        "price":         6400.00,
        "currency":      "USD",
        "weight_kg":     65.0,
        "dimensions_cm": "82x62x145",
        "is_active":     True,
    },
    {
        "product_id":    "TRBT-010",
        "sku":           "TRBT-MIXTRAL-MIXIOTE",
        "name":          "Mixtral Mixiote Pro",
        "description":   "Lamb mixiote robot with 8 expert flavor heads. Each expert handles a different chili dimension.",
        "price":         7200.00,
        "currency":      "USD",
        "weight_kg":     72.0,
        "dimensions_cm": "90x70x155",
        "is_active":     True,
    },
    # ── Accessories ───────────────────────────────────────────────────────────
    {
        "product_id":    "ACC-001",
        "sku":           "ACC-TORTILLA-PRESS-X1",
        "name":          "TortillaPress X1",
        "description":   "Pneumatic tortilla press module. 300 tortillas/hr. Compatible with all TRBT-series robots.",
        "price":         349.00,
        "currency":      "USD",
        "weight_kg":     4.2,
        "dimensions_cm": "30x30x20",
        "is_active":     True,
    },
    {
        "product_id":    "ACC-002",
        "sku":           "ACC-SALSA-MULTIBANK-5",
        "name":          "SalsaBank 5-Channel",
        "description":   "5-channel salsa dispenser with AI portion control. USB-C connection. Fits all TRBT-series.",
        "price":         199.99,
        "currency":      "USD",
        "weight_kg":     2.1,
        "dimensions_cm": "40x15x20",
        "is_active":     True,
    },
    {
        "product_id":    "ACC-003",
        "sku":           "ACC-CILANTRO-DISP-V3",
        "name":          "CilantroBot Dispenser v3",
        "description":   "Micro-servo cilantro and onion chopper. Gram-level portion precision. 500g refill capacity.",
        "price":         89.00,
        "currency":      "USD",
        "weight_kg":     0.8,
        "dimensions_cm": "10x10x25",
        "is_active":     True,
    },
    {
        "product_id":    "ACC-004",
        "sku":           "ACC-LASER-LIME-V1",
        "name":          "LaserLime Squeezer v1",
        "description":   "Automated lime squeezer with laser targeting. Adjustable squirt radius 5–30cm. 99.1% coverage.",
        "price":         120.00,
        "currency":      "USD",
        "weight_kg":     1.1,
        "dimensions_cm": "15x12x18",
        "is_active":     True,
    },
    {
        "product_id":    "ACC-005",
        "sku":           "ACC-AVOCADO-ARM-PRO",
        "name":          "AvocadoArm Pro",
        "description":   "Robotic arm for avocado slicing, mashing, and guac dispensing. Ripeness detection via spectral sensor.",
        "price":         450.00,
        "currency":      "USD",
        "weight_kg":     5.5,
        "dimensions_cm": "35x25x40",
        "is_active":     False,
    },
    # ── Consumables ───────────────────────────────────────────────────────────
    {
        "product_id":    "CONS-001",
        "sku":           "CONS-CORNMIX-25KG",
        "name":          "MasaCore Corn Mix 25kg",
        "description":   "Pre-mixed corn masa calibrated for TacoBot presses. 47% moisture. Yields ~500 tortillas per bag.",
        "price":         45.00,
        "currency":      "USD",
        "weight_kg":     25.0,
        "dimensions_cm": "50x30x20",
        "is_active":     True,
    },
    {
        "product_id":    "CONS-002",
        "sku":           "CONS-LUBRICANT-FOOD-1L",
        "name":          "FoodSafe Lube 1L",
        "description":   "NSF H1-certified food-safe lubricant for all TacoBot joints. Required every 500 operating hours.",
        "price":         22.50,
        "currency":      "USD",
        "weight_kg":     1.05,
        "dimensions_cm": "8x8x25",
        "is_active":     True,
    },
    {
        "product_id":    "CONS-003",
        "sku":           "CONS-HABANERO-PASTE-5KG",
        "name":          "HabaneroCore Paste 5kg",
        "description":   "Industrial habanero paste for Cochinita and RLHF-Habanero models. Scoville-calibrated at 250k SHU.",
        "price":         38.00,
        "currency":      "USD",
        "weight_kg":     5.0,
        "dimensions_cm": "20x20x15",
        "is_active":     True,
    },
    # ── Software & Services ───────────────────────────────────────────────────
    {
        "product_id":    "SVC-001",
        "sku":           "SVC-CLOUD-DASHBOARD-MO",
        "name":          "TacoCloud Dashboard (monthly)",
        "description":   "Real-time SaaS dashboard: tacos/hr, salsa levels, error logs, predictive maintenance alerts. 99.9% uptime SLA.",
        "price":         79.00,
        "currency":      "USD",
        "weight_kg":     0.0,
        "dimensions_cm": "N/A",
        "is_active":     True,
    },
    {
        "product_id":    "SVC-002",
        "sku":           "SVC-MODEL-FINETUNE-MX",
        "name":          "Flavor Model Fine-Tune Pack MX",
        "description":   "Custom fine-tuning of your robot's flavor model on up to 500 proprietary recipes. Delivered as OTA update in 5 days.",
        "price":         1200.00,
        "currency":      "USD",
        "weight_kg":     0.0,
        "dimensions_cm": "N/A",
        "is_active":     True,
    },
]